---
title: "plot_timecourses"
author: "Dani Cosme"
date: "10/17/2017"
output:
  md_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning= FALSE, fig.width = 10, fig.height = 5, dpi = 150)
```

# load packages
```{r}
library(tidyverse)
library(wesanderson)
```

# load data
```{r}
data = read.csv('/Volumes/psych-cog/dsnlab/FP/BDX_univariate/timecourses/timecourses.csv')
```

# tidy data for plotting
```{r}
# set colot palette
palette = wes_palette("Zissou", 4, type = "continuous")

# filter out conditions of no interest and rearrange factor levels for plotting
plot.data = data %>%
  filter(condition %in% c("HighLook", "HighRegulate", "LowLook", "LowRegulate")) 

# add additional information 
plot.data = plot.data %>%
  mutate(condition = factor(condition, levels = c("LowLook", "HighLook", "LowRegulate", "HighRegulate")),
         autonomy = ifelse(condition %in% c("LowLook", "LowRegulate"), "low", "high"),
         action = ifelse(condition %in% c("LowLook", "HighLook"), "look", "regulate"),
         seconds = tr*2)
```

# plot data with LOESS curves
## All conditions
Lines = rating, report, fixation
```{r}
ggplot(plot.data, aes(seconds, percentChange, color = condition)) +
  geom_smooth(alpha = .25) + 
  geom_vline(xintercept = c(7, 11, 13), alpha = .5) + 
  facet_grid(~roi) +
  scale_color_manual(values=palette) + 
  labs(x = "time (seconds)", y = "percent signal change")+ 
  scale_x_continuous(breaks = seq(0,20,2))
```

# plot data with LOESS curves by action
## By action
Lines = rating, report, fixation
```{r}
ggplot(plot.data, aes(seconds, percentChange, color = condition)) +
  geom_smooth(alpha = .25) + 
  geom_vline(xintercept = c(7, 11, 13), alpha = .5) + 
  facet_grid(action ~ roi) +
  scale_color_manual(values=palette) + 
  labs(x = "time (seconds)", y = "percent signal change") + 
  scale_x_continuous(breaks = seq(0,20,2))
```

# plot means and CIs
## All conditions
Lines = rating, report, fixation
```{r}
ggplot(plot.data, aes(seconds, percentChange, color = condition)) +
  stat_summary(fun.y = mean, geom = "line", size = 1.25) + 
  stat_summary(fun.data = mean_cl_normal, geom = "pointrange", alpha = .5) +
  geom_vline(xintercept = c(7, 11, 13), alpha = .5) + 
  facet_grid(~roi) +
  scale_color_manual(values=palette) + 
  labs(x = "time (seconds)", y = "percent signal change") + 
  scale_x_continuous(breaks = seq(0,20,2))
```

## By action
Lines = rating, report, fixation
```{r}
ggplot(plot.data, aes(seconds, percentChange, color = condition)) +
  stat_summary(fun.y = mean, geom = "line", size = 1.25) + 
  stat_summary(fun.data = mean_cl_normal, geom = "pointrange", alpha = .5) +
  geom_vline(xintercept = c(7, 11, 13), alpha = .5) + 
  facet_grid(action ~ roi) +
  scale_color_manual(values=palette) + 
  labs(x = "time (seconds)", y = "percent signal change") + 
  scale_x_continuous(breaks = seq(0,20,2))
```